---
title: "08_depth_reef_figures"
author: "Gemma Galbraith"
date: "30/05/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#HouseKeeping
```{R}
rm(list=ls())
#dev.off()
getwd()

```

#load libraries
```{r}
library(tidyverse)
library(rfishbase)
library(vegan)
library(glmmTMB)
library(sjPlot)
library(DHARMa)
library(car)
library(emmeans)
library(tidyverse)
library(broom.mixed)
library(ggpubr)
library(gridExtra)
library(svglite)
library(lubridate)
library(viridis)  
library(RColorBrewer)
library(unikn)
```

# My colours
#F2C249
#E6772E
#4DB3B3
#E64A45
#3D4C53
#a54a9c
#5074c3

```{r}
my.cols = c("#F2C249", "#E6772E", "#4DB3B3", "#E64A45", "#3D4C53", "#a54a9c", "#5074c3")

seecol(my.cols, 
       col_brd = "black", lwd_brd = 2, 
       title = "See the colors, HEX codes, and RGB values of my.cols") 

depth.cols <- c("#F2C249", "#4DB3B3", "#a54a9c")

seecol(depth.cols, 
       col_brd = "black", lwd_brd = 2, 
       title = "See the colors, HEX codes, and RGB values of my.cols") 
```


# Data import
```{r}
diversity <-read_csv("../0_data/fish_diversity.csv")
biomass <-read_csv("../0_data/fish_biomass.csv")
biomass<-biomass %>% select(T_ID, Total_Biomass_g)

fish<-left_join(diversity, biomass, by="T_ID")

fish <- fish %>% mutate(
  Reef=as.factor(Reef),
  T_ID=as.factor(T_ID),
  Survey=as.factor(Survey),
  Site=as.factor(Site),
  Date = as.Date(Date),
  Habitat = as.factor(Habitat),
  Aspect = as.factor(Aspect),
  Total_biomass_KG = as.double(Total_Biomass_g/1000))

```


# apply Region grouping by reef
```{r}
fish <- fish %>% mutate ( 
  Region = as.factor(case_when(grepl("Lihou", Reef) ~ "Central Coral Sea",
                   grepl("Flinders", Reef) ~ "Central Coral Sea",
                   grepl("Bougainville", Reef) ~ "Northern Coral Sea",
                   grepl("Osprey", Reef) ~ "Northern Coral Sea",
                   grepl("Chillcot", Reef) ~ "Central Coral Sea",
                   grepl("Herald", Reef) ~ "Central Coral Sea",
                   grepl("Holmes", Reef) ~ "Central Coral Sea",
                   grepl("Willis", Reef) ~ "Central Coral Sea",
                   grepl("Frederick", Reef) ~ "Southern Coral Sea",
                   grepl("Kenn", Reef) ~ "Southern Coral Sea",
                   grepl("Wreck", Reef) ~ "Southern Coral Sea",
                   grepl("Saumarez", Reef) ~ "Southern Coral Sea",
                   grepl("Marion", Reef) ~ "Central Coral Sea",)))

unique(fish$Region)
# Should just be three levels

# Ordered factor for Region
fish <-fish %>% mutate(
  Region = factor(Region, levels= c("Southern Coral Sea","Central Coral Sea","Northern Coral Sea"),ordered = TRUE))
```

# Assign Depth grouping
```{r}
fish <- fish %>% mutate(
  Depth_bin = as.factor(case_when(Depth < 30 ~ "Shallow",
                                  Depth > 30 & Depth < 65 ~ "Mid",
                                  TRUE ~ "Deep"))
)

unique(fish$Depth_bin)

# Ordered factor for Region
fish <-fish %>% mutate(
  Depth_bin = factor(Depth_bin, levels= c("Shallow","Mid","Deep"),
                                         ordered = TRUE))
```

# Richness boxplots

```{R} 
P1<-ggplot(fish, aes(y=richness, x=Reef, fill =Depth_bin)) + 
  geom_boxplot(outlier.colour="black", outlier.shape=16,
             outlier.size=2, notch=FALSE)+
  scale_fill_manual(values = depth.cols, name = "Depth Bin")+
  ylab(expression(Richness~("Species 150m"^-2 %+-%SE)))+
  xlab("")+
  scale_y_continuous(expand = c(0, 0), limits = c(0, 50))+ 
  facet_grid(cols = vars(Region), scales = "free", space ="free")+
theme_classic()+
  theme(axis.text.x = element_text(size=14, color="black", angle = 45, vjust = 0.6),
        axis.text.y = element_text(size=14, color="black"),
        axis.title.y = element_text(size=16, vjust=2),
        axis.title.x = element_text(size=16, vjust=-0.2),
        legend.position = "bottom",
        legend.text = element_text(size=14, color="black"),
         legend.title = element_text(size=16, color="black"),
        strip.text = element_text(size = 14, colour = "black", face = "bold"),
        strip.background = element_blank())


ggsave(filename = "../3_figures/depth_REEF_richness.png", plot= P1,
       width =300, height=150 , units = "mm", dpi = 500, device = "png" )


```

# ABUNDANCE/DENSITY boxplots

```{R} 
P2<-ggplot(fish, aes(y=abundance, x=Reef, fill =Depth_bin)) + 
  geom_boxplot(outlier.colour="black", outlier.shape=16,
             outlier.size=2, notch=FALSE)+
  scale_fill_manual(values = depth.cols, name = "Depth Bin")+
  ylab(expression(Density~("n 150m"^-2 %+-%SE)))+
  xlab("")+
  scale_y_continuous(expand = c(0, 0), limits = c(0, 500))+ 
  facet_grid(cols = vars(Region), scales = "free", space ="free")+
theme_classic()+
  theme(axis.text.x = element_text(size=14, color="black", angle = 45, vjust = 0.6),
        axis.text.y = element_text(size=14, color="black"),
        axis.title.y = element_text(size=16, vjust=2),
        axis.title.x = element_text(size=16, vjust=-0.2),
        legend.position = "bottom",
        legend.text = element_text(size=14, color="black"),
         legend.title = element_text(size=16, color="black"),
        strip.text = element_text(size = 14, colour = "black", face = "bold"),
        strip.background = element_blank())

P2

ggsave(filename = "../3_figures/depth_REEF_abundance.png", plot= P2,
       width =300, height=150 , units = "mm", dpi = 500, device = "png" )


```

# Diversity boxplots

```{R} 
P3<-ggplot(fish, aes(y=shannon, x=Reef, fill =Depth_bin)) + 
  geom_boxplot(outlier.colour="black", outlier.shape=16,
             outlier.size=2, notch=FALSE)+
  scale_fill_manual(values = depth.cols, name = "Depth Bin")+
  ylab(expression(Diversity~("H' 150m"^-2 %+-%SE)))+
  xlab("")+
  scale_y_continuous(expand = c(0, 0), limits = c(0, 5))+ 
  facet_grid(cols = vars(Region), scales = "free", space ="free")+
theme_classic()+
  theme(axis.text.x = element_text(size=14, color="black", angle = 45, vjust = 0.6),
        axis.text.y = element_text(size=14, color="black"),
        axis.title.y = element_text(size=16, vjust=2),
        axis.title.x = element_text(size=16, vjust=-0.2),
        legend.position = "bottom",
        legend.text = element_text(size=14, color="black"),
         legend.title = element_text(size=16, color="black"),
        strip.text = element_text(size = 14, colour = "black", face = "bold"),
        strip.background = element_blank())

P3

ggsave(filename = "../3_figures/depth_REEF_diversity.png", plot= P3,
       width =300, height=150 , units = "mm", dpi = 500, device = "png" )


```


# Biomass by depth and Reef
```{R} 
P4<-ggplot(fish, aes(y=Total_biomass_KG, x=Reef, fill =Depth_bin)) + 
  geom_boxplot(outlier.colour="black", outlier.shape=16,
             outlier.size=2, notch=FALSE)+
  scale_fill_manual(values = depth.cols, name = "Depth Bin")+
  ylab(expression(Biomass~("Kg 150m"^-2 %+-%SE)))+
  xlab("")+
  scale_y_continuous(expand = c(0, 0), limits = c(0, 300))+ 
  facet_grid(cols = vars(Region), scales = "free", space ="free")+
theme_classic()+
  theme(axis.text.x = element_text(size=14, color="black", angle = 45, vjust = 0.6),
        axis.text.y = element_text(size=14, color="black"),
        axis.title.y = element_text(size=16, vjust=2),
        axis.title.x = element_text(size=16, vjust=-0.2),
        legend.position = "bottom",
        legend.text = element_text(size=14, color="black"),
         legend.title = element_text(size=16, color="black"),
        strip.text = element_text(size = 14, colour = "black", face = "bold"),
        strip.background = element_blank())

P4

ggsave(filename = "../3_figures/depth_REEF_diversity.png", plot= P3,
       width =300, height=150 , units = "mm", dpi = 500, device = "png" )


```
 
# Combined Figure - needs text size tweaking and only one REGION header
```{r}
ggarrange(P1,P2, ncol = 1, lables = c("A","B"))

```
